baseurl: ""
url: ""

collections_dir: collections
permalink: pretty

exclude:
  - docker-compose.yml
  - README.md
  - .gitignore

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Disqus Comments
disqus:
  enable: false # disque is enabled. Set as false to disable it
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: dexfolio